# SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
filter:
    excluded_paths:
        - 'js/jquery*'
        - 'l10n/*'
        - 'tests/*'

imports:
    - javascript
    - php
